server:
  port: 80

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      authentication-database: admin
      database: my-database
      username: DDonghyeo
      password: 1234