server:
  port: 80

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      authentication-database: admin
      database: my-database
      username: DDonghyeo
      password: 1234


mail:
  smtp:
    port: 465
    auth: true
    starttls:
      required: true
      enable: true
    socketFactory:
      class: javax.net.ssl.SSLSocketFactory
      fallback: false
      port: 465

AdminMail:
  id: mailmail@gmail.com
  password: password


jwt:
  secret: 6B64DCA4E72F58EDIKU9AAB215FE7